.TH UVI 1 UVI\-0.9
.SH NAME
uvi \- vi like text editor
.SH SYNOPSIS
.B uvi
.RB FILEs...
.SH DESCRIPTION
uvi description goes here - TODO
.SH OPTIONS
.TP
.B \-R
Make all opened buffers readonly
.TP
.B +cmd
Execute cmd (place characters in read buffer) at startup
.SH NOTES
Still buggy, see TODO
.SH SEE ALSO
.BR vi (1)
.SH BUGS
Yes. See TODO
